name: Windows Performance Test
on: [pull_request]

jobs:

  test_cmd_make_all:
    name: Test cmd make all
    runs-on: windows-latest
    steps:
      - name: Git Configure
        shell: bash
        run: git config --global core.autocrlf input
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: make all with cmd
        shell: cmd
        run: make all
